# List of slash (/) commands
slash-name:
  tuuck:             "/tuuck"
  version:           "/version"
  coin-flip:         "/coin-flip"
  insult:            "/insult"
  play:              "/play"
  stop:              "/stop"
  queue:             "/queue"
  clear:             "/clear"
  pick-choices:      "/pick choices"
  pick-steam:        "/pick steam"
  animals-doggo:     "/animals doggo"
  daily-horoscope:   "/daily horoscope"
  daily-affirmation: "/daily affirmation"
  daily-advice:      "/daily advice"
  daily-kanye:       "/daily kanye"

# List of prefix ($) commands
pref-name:
  start-server:  "$startServer"
  stop-server:   "$stopServer"
  server-status: "$serverStatus"

# Command Descriptions
description:
  tuuck:             "Lists available commands."
  start-server:      "Starts Minecraft Server."
  stop-server:       "Stops Minecraft Server."
  server-status:     "Gives the current status of the MC server."
  version:           "Gives the Git SHA of the current bot version running"
  coin-flip:         "Flips a coin, sends gif for results"
  lmgtfy:            "Add the :grey_question: Reaction to a message and get a LMGTFY link"
  insult:            "Sends an insult and tags {@User}"
  play:              "Adds youtube audio to queue and plays it"
  stop:              "Stops the audio link playback"
  queue:             "Gets the current song queue"
  clear:             "Clears the audio queue"
  pick-choices:      "Chooses between 2 or more things."
  pick-steam:        "Chooses random steam game."
  animals-doggo:     "Gives doggo."
  daily-horoscope:   "Gives daily horoscope."
  daily-affirmation: "Gives daily affirmation."
  daily-advice:      "Gives daily advice."
  daily-kanye:       "Gives daily kanye."

# Command Usage Examples
example:
  tuuck:             "/tuuck"
  start-server:      "$startServer"
  stop-server:       "$stopServer"
  server-status:     "$serverStatus"
  version:           "/version"
  coin-flip:         "/coin-flip"
  lmgtfy:            "Add the :grey_question: Reaction to a channel message"
  insult:            "/insult `user: @BuddieBot`"
  play:              "/play `link: https://www.youtube.com/watch?v=dQw4w9WgXcQ`"
  stop:              "/stop"
  queue:             "/queue"
  clear:             "/clear"
  pick-choices:      "/pick choices `1st: option1` `2nd: option2`"
  pick-steam:        "/pick steam"
  animals-doggo:     "/animals doggo"
  daily-horoscope:   "/daily horoscope"
  daily-affirmation: "/daily affirmation"
  daily-advice:      "/daily advice"
  daily-kanye:       "/daily kanye"

# Static cmd related messages
message:
  windUp:           "`*starts minecraft server in silence*`"
  windDown:         "stopping minecraft server, Alt-F4 really speeds things up 0.0"
  finishOpperation: "`*beep boop* All done. Powered by Duracell™️`"
  serverUP:         "Did you even try to connect first, Ding-Dong? It's already running. "
  serverDOWN:       "Someone must've beat you to it. Server isn't running. "
  checkStatusUp:    "Rocking and rolling, my guy. "
  checkStatusDown:  "Server is down. ¯\\_(ツ)_/¯ I just work here."
  invalid:          "UwU you did a oopsy poopsy! Try '$tuuck' for swum big swong hewlp >.<"
  notBotAdmin:      "XD sowwy, you need spwecial pewrmission to dew dat."
  tenorAPIError:    "UwU dere was a prawblum with the Tenor API :("
  youtubeAPIError:  "UwU dere was a prawblum with the Youtube API :("
  insultAPIError:   "UwU dere was a prawblum with the Insult API :("
  mcServerError:    "UwU dere was a prawblum with the Insult API :("