# Displayed when the '/tuuck' cmd is called
name:
  list-tuuck: "/tuuck"
  list-horoscope: "/horoscope"
  list-version: "/version"
  list-coin-flip: "/coin-flip"
  list-insult: "/insult"
  list-play: "/play"
  list-stop: "/stop"
  list-queue: "/queue"
  list-clear: "/clear"
  list-pick: "/pick"

description:
  desc-tuuck: Lists available commands."
  desc-start-server: "Starts Minecraft Server."
  desc-stop-server: "Stops Minecraft Server."
  desc-horoscope: "Gives daily horoscope."
  desc-server-status: "Gives the current status of the MC server."
  desc-version: "Gives the Git SHA of the current bot version running"
  desc-coin-flip: "Flips a coin, sends gif for results"
  desc-lmgtfy: "Add the 'Ask' Reaction to a msg and get a LMGTFY link"
  desc-insult: "Sends an insult and tags {@User}"
  desc-play: "Adds youtube audio to queue and plays it"
  desc-stop: "Stops the audio link playback"
  desc-queue: "Gets the current song queue"
  desc-clear: "Clears the audio queue"
  desc-pick: "Chooses between 2 or more things. Can even pick a random steam game to play"

# Static cmd related messages
message:
  windUp: "`*starts minecraft server in silence*`"
  windDown: "stopping minecraft server, Alt-F4 really speeds things up 0.0"
  finishOpperation: "`*beep boop* All done. Powered by Duracell™️`"
  serverUP: "Did you even try to connect first, Ding-Dong? It's already running. "
  serverDOWN: "Someone must've beat you to it. Server isn't running. "
  checkStatusUp: "Rocking and rolling, my guy. "
  checkStatusDown: "Server is down. ¯\\_(ツ)_/¯ I just work here."
  invalid: "UwU you did a oopsy poopsy! Try '$tuuck' for swum big swong hewlp >.<"
  notBotAdmin: "XD sowwy, you need spwecial pewrmission to dew dat."
  tenorAPIError: "UwU dere was a prawblum with the Tenor API :("
  youtubeAPIError: "UwU dere was a prawblum with the Youtube API :("
  insultAPIError: "UwU dere was a prawblum with the Insult API :("
  mcServerError: "UwU dere was a prawblum with the Insult API :("