name: Deploy API

on:
  push:
    branches:
      - master

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      #      - name: Test
      #        run:  |
      #              go test -v ./...

      - name: Build
        run:  |
              go get ./...
              go get -u layeh.com/gopus
              go build -o buddiebot_server cmd/discord-bot/main.go


      - name: Create build dirs
        uses: appleboy/ssh-action@master
        env:
          GITHUB_SHA: ${{ github.sha }}
        with:
          host:     ${{ secrets.EC2_HOST_NAME }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          envs:     GITHUB_SHA
          script:   |
                    mkdir -p $GITHUB_SHA
                    ${{ secrets.CONFIG_KEYS }} > config_files/config.yaml
                    mkdir -p $GITHUB_SHA/config_files


      - name: Send build file to server
        uses: appleboy/scp-action@master
        env:
          GITHUB_SHA: ${{ github.sha }}
        with:
          host:     ${{ secrets.EC2_HOST_NAME }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          source:   "./buddiebot_server"
          target:   "/home/ubuntu/$GITHUB_SHA/"


      - name: Send config files to server
        uses: appleboy/scp-action@master
        env:
          GITHUB_SHA: ${{ github.sha }}
        with:
          host:     ${{ secrets.EC2_HOST_NAME }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          source:   "config_files/config.yaml, config_files/cmd.yaml, config_files/bot.service, config_files/loading_messages.txt, config_files/emojis.txt, config_files/text_fonts.json"
          target:   "/home/ubuntu/$GITHUB_SHA/config_files/"


      - name: Stop and restart service
        uses: appleboy/ssh-action@master
        env:
          GITHUB_SHA: ${{ github.sha }}
        with:
          host:     ${{ secrets.EC2_HOST_NAME }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          envs:     GITHUB_SHA
          script:   |
                    cd $GITHUB_SHA/config_files; sudo mv bot.service /etc/systemd/system; cd /etc/systemd/system; sudo systemctl daemon-reload; sudo systemctl enable bot.service; sudo systemctl start bot.service
                    unlink current; ln -s $GITHUB_SHA current
                    sudo systemctl restart bot.service
                    sudo rm -rf $(ls -t -r | head -n 1)

#      - name: Use gcloud CLI
#        run:  gcloud info
#
#        # sudo apt-get install -y g++ libgtk-3-dev libfreetype6-dev libx11-dev libxinerama-dev libxrandr-dev libxcursor-dev mesa-common-dev libasound2-dev freeglut3-dev libxcomposite-dev libcurl4-openssl-dev
#        # sudo apt-get install software-properties-common
#        # sudo add-apt-repository -r ppa:webkit-team/ppa && sudo apt-get install libwebkit2gtk-4.0-37 libwebkit2gtk-4.0-dev
#
#      - name: Upload new server binary and install packages
#        run:  |
#              gcloud compute ssh --strict-host-key-checking=no --zone=us-central1-a colerwyats@discord-bot --command="mkdir ${GITHUB_SHA}"
#              gcloud compute scp --strict-host-key-checking=no --zone=us-central1-a ./buddiebot_server colerwyats@discord-bot:/home/colerwyats/${GITHUB_SHA}
#
#      - name: Upload new configs from secret
#        run:  |
#              echo '${{ secrets.GCP_SSH_KEY }}' > config_files/config.yaml
#
#              gcloud compute ssh --strict-host-key-checking=no --zone=us-central1-a colerwyats@discord-bot --command="mkdir ${GITHUB_SHA}/config_files"
#              gcloud compute scp --strict-host-key-checking=no --zone=us-central1-a config_files/config.yaml colerwyats@discord-bot:/home/colerwyats/${GITHUB_SHA}/config_files
#              gcloud compute scp --strict-host-key-checking=no --zone=us-central1-a config_files/cmd.yaml colerwyats@discord-bot:/home/colerwyats/${GITHUB_SHA}/config_files
#              gcloud compute scp --strict-host-key-checking=no --zone=us-central1-a config_files/bot.service colerwyats@discord-bot:/home/colerwyats/${GITHUB_SHA}/config_files
#              gcloud compute scp --strict-host-key-checking=no --zone=us-central1-a config_files/loading_messages.txt colerwyats@discord-bot:/home/colerwyats/${GITHUB_SHA}/config_files
#              gcloud compute scp --strict-host-key-checking=no --zone=us-central1-a config_files/emojis.txt colerwyats@discord-bot:/home/colerwyats/${GITHUB_SHA}/config_files
#              gcloud compute scp --strict-host-key-checking=no --zone=us-central1-a config_files/text_fonts.json colerwyats@discord-bot:/home/colerwyats/${GITHUB_SHA}/config_files
#
#      - name: Stop old service and start new
#        run:  |
#              gcloud compute ssh --strict-host-key-checking=no --zone=us-central1-a colerwyats@discord-bot --command="cd ${GITHUB_SHA}/config_files; sudo mv bot.service /etc/systemd/system; cd /etc/systemd/system; sudo systemctl daemon-reload; sudo systemctl enable bot.service; sudo systemctl start bot.service"
#              gcloud compute ssh --strict-host-key-checking=no --zone=us-central1-a colerwyats@discord-bot --command="unlink current; ln -s ${GITHUB_SHA} current"
#              gcloud compute ssh --strict-host-key-checking=no --zone=us-central1-a colerwyats@discord-bot --command="sudo systemctl restart bot.service"
#              gcloud compute ssh --strict-host-key-checking=no --zone=us-central1-a colerwyats@discord-bot --command="sudo rm -rf $(ls -t -r | head -n 1)"