name: Deploy API

on:
  push:
    branches:
      - master

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.0

      #      - name: Test
      #        run:  |
      #              go test -v ./...

      - name: Build
        run:  |
              go get ./...
              go get -u layeh.com/gopus
              go build -o buddiebot_server cmd/discord-bot/main.go

      #- name: Debug Network Connection
       # run: |
        #  ping -c 4 ${{ secrets.HOST_IP }}
        #  nc -zv ${{ secrets.HOST_IP }} 22
      
      - name: Send build file to server
        uses: appleboy/scp-action@master
        with:
                host:     ${{ secrets.HOST_IP }}
                username: ${{ secrets.HOST_USERNAME }}
                password: ${{ secrets.HOST_PASSWORD }}
                port:     22
                #key:      ${{ secrets.RSA_KEY }}
                source:   "./buddiebot_server"
                target:   "/home/${{ secrets.HOST_USERNAME }}/${{ github.sha }}"
      
      
      - name: Send config files to server
        uses: appleboy/scp-action@master
        with:
                host:     ${{ secrets.HOST_IP }}
                username: ${{ secrets.HOST_USERNAME }}
                password: ${{ secrets.HOST_PASSWORD }}
                port:     22
                #key:      ${{ secrets.RSA_KEY }}
                source:   "config_files/config.yaml,config_files/cmd.yaml,config_files/bot.service,config_files/loading_messages.txt,config_files/emojis.txt,config_files/text_fonts.json"
                target:   "/home/${{ secrets.HOST_USERNAME }}/${{ github.sha }}"


      - name: Stop and restart service
        #        uses: appleboy/ssh-action@master
        #        with:
        #          host:     ${{ secrets.EC2_HOST_NAME }}
        #          username: ${{ secrets.HOST_USERNAME }}
        #          password: ${{ secrets.HOST_PASSWORD }}
        run:  |
              echo This is working
#                    echo '${{ secrets.CONFIG_KEYS }}' > ${{ github.sha }}/config_files/config.yaml
#
#                    sudo mv ${{ github.sha }}/config_files/bot.service /etc/systemd/system
#                    cd /etc/systemd/system
#                    sudo systemctl daemon-reload
#                    sudo systemctl enable bot.service
#                    sudo systemctl start bot.service
#                    sudo unlink current
#                    if [ -d /home/ubuntu/current_build ]; then sudo mv /home/ubuntu/current_build /home/ubuntu/previous_build; fi
#                    sudo mv /home/ubuntu/${{ github.sha }} /home/ubuntu/current_build
#                    sudo ln -sf current_build current
#                    sudo rm -rf previous_build
#                    sudo systemctl restart bot.service
