name: Deploy API

on:
  push:
    branches:
      - master

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      #      - name: Test
      #        run:  |
      #              go test -v ./...

      - name: Build
        run:  |
              go get ./...
              go get -u layeh.com/gopus
              go build -o buddiebot_server cmd/discord-bot/main.go


      - name: Send build file to server
        uses: appleboy/scp-action@master
        with:
          host:     ${{ secrets.EC2_HOST_NAME }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          source:   "./buddiebot_server"
          target:   "/home/ubuntu/${{ github.sha }}"


      - name: Send config files to server
        uses: appleboy/scp-action@master
        with:
          host:     ${{ secrets.EC2_HOST_NAME }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          source:   "config_files/config.yaml,config_files/cmd.yaml,config_files/bot.service,config_files/loading_messages.txt,config_files/emojis.txt,config_files/text_fonts.json"
          target:   "/home/ubuntu/${{ github.sha }}"


      - name: Create build dirs
        uses: appleboy/ssh-action@master
        with:
          host:     ${{ secrets.EC2_HOST_NAME }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          script:   |
                    echo '${{ secrets.CONFIG_KEYS }}' > ${{ github.sha }}/config_files/config.yaml


      - name: Stop and restart service
        uses: appleboy/ssh-action@master
        with:
          host:     ${{ secrets.EC2_HOST_NAME }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          script:   |
                    cd ${{ github.sha }}/config_files
                    sudo mv bot.service /etc/systemd/system
                    cd /etc/systemd/system
                    sudo systemctl daemon-reload
                    sudo systemctl enable bot.service
                    sudo systemctl start bot.service
                    
                    sudo ln -sf ${{ github.sha }} current
                    sudo chflags -h ${{ github.sha }}
                    sudo systemctl restart bot.service
                    sudo rm -rf $(ls -t -r | head -n 1)

          #                      sudo unlink current