name: Deploy API

on:
  push:
    branches:
    - master

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: |
        go get ./...
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o discord_server main.go

    # Need to reimplement after unit test are seperated from integration tests
    # - name: Test
    #   run: go test -v ./...

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
      
    - name: Use gcloud CLI
      run: gcloud info

    - name: Upload new server binary
      run: |
        gcloud compute ssh --strict-host-key-checking=no --zone=us-central1-c colerwyats@hopper-instance-1 --command="mkdir ${GITHUB_SHA}"
        gcloud compute scp --strict-host-key-checking=no --zone=us-central1-c ./discord_server colerwyats@hopper-instance-1:/home/colerwyats/${GITHUB_SHA}

    - name: Upload new configs from secret
      run: |
        echo '${{ secrets.GCP_SA_KEY }}' > config/auth.json
        echo '${{ secrets.GCP_SSH_KEY }}' > config/config.json

        gcloud compute ssh --strict-host-key-checking=no --zone=us-central1-c colerwyats@hopper-instance-1 --command="mkdir ${GITHUB_SHA}/config"

        gcloud compute scp --strict-host-key-checking=no --zone=us-central1-c config/auth.json colerwyats@hopper-instance-1:/home/colerwyats/${GITHUB_SHA}/config
        gcloud compute scp --strict-host-key-checking=no --zone=us-central1-c config/config.json colerwyats@hopper-instance-1:/home/colerwyats/${GITHUB_SHA}/config

    #### TODO KILL SERVICE BEFORE STARTING NEW ONE IN BACKGROUND (need to inspect ps when deployed)

    - name: Stop old service and start new
      run: |
        gcloud compute ssh --strict-host-key-checking=no --zone=us-central1-c colerwyats@hopper-instance-1 --command="cd ${GITHUB_SHA}; pkill -f "discord_server"; ./discord_server &"